apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU193emI4VGp1SExRNl9raHUwWWY2QG5sdy11bml0ZS1kby11c2VyLTExODUxNzgtMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9ubHctdW5pdGU/c3NsbW9kZT1yZXF1aXJl